version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: mimi_user
      POSTGRES_PASSWORD: mimi_password
      POSTGRES_DB: mimi_db_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_test:
    image: postgres:15
    environment:
      POSTGRES_USER: mimi_user
      POSTGRES_PASSWORD: mimi_password
      POSTGRES_DB: mimi_db_test
    ports:
      - "5433:5432"

volumes:
  postgres_data:

