services:
  db:
    image: postgres:17
    # restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: mimi
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data

